### ISSUE TITLE
`subscribe` command fails consistently

### ISSUE THREAD

**Issue by jdkaplan** [recursecenter/pairing-bot#66]
The `subscribe` command seems to be failing with a 404 from the Recurse Center API. 

## Reproducing steps

1. Send `unsubscribe`
2. Send `subscribe`
3. Receive "something went sideways" error message

## Other notes

Originally reported in [Zulip](https://recurse.zulipchat.com/#narrow/stream/198090-rc-community-software/topic/pairing.20not.20-.20something.20went.20sideways/near/459537549)

The most specific error message I see is from https://github.com/recursecenter/pairing-bot/blob/09a09c068d3eeae287895efbbb2120888e1f7beb/api.go#L39-L39

> Could not read currently-at-RC data from database: while reading from offset 0: HTTP error while getting active RCers from the RC API: 404 Not Found

**Comment by cceckman** [comment]
(From what I saw), the RC API turns up 404 on authentication issues; we should check the tokens used to talk to the API.

**Comment by cceckman** [comment]
I swapped the (unused) `rc-apiauth` value into the (used) `rc-accesstoken` value; the `rc-accesstoken` value worked for a manual request.

I was able to unsubscribe and subscribe successfully after that.

**Comment by jdkaplan** [comment]
Thanks for the fix! You got to it before I even got a chance to look at the code any further. Which is good, because the 404 was about to send me looking at how we build the request rather than toward the API key. I would have expected a 401 Unauthorized instead :shrug: 

I can't think of any other changes I want to make in response to this, so... closing!
