### ISSUE TITLE
Use Firestore struct tags for field mapping

### ISSUE THREAD

**Issue by jdkaplan** [recursecenter/pairing-bot#83]
The Firestore client can use a `firestore` struct tag to map between Firestore documents and Go structs. We should use it! 

For example, this is (now) how we map the Recurser struct (just like the standard library's `json` tag):
```go
type Recurser struct {
	ID                 int64           `firestore:"id"`
	Name               string          `firestore:"name"`
	Email              string          `firestore:"email"`
	IsSkippingTomorrow bool            `firestore:"isSkippingTomorrow"`
	Schedule           map[string]bool `firestore:"schedule"`
	CurrentlyAtRC      bool            `firestore:"currentlyAtRC"`

	// IsSubscribed really means "already had an entry in the database".
	// It is not written to or read from the Firestore document.
	IsSubscribed bool `firestore:"-"`
}
```

Relevant docs:
- [DocumentSnapshot.DataTo](https://pkg.go.dev/cloud.google.com/go/firestore@v1.14.0#DocumentSnapshot.DataTo)
- [DocumentRef.Create](https://pkg.go.dev/cloud.google.com/go/firestore@v1.14.0#DocumentRef.Create)

## Tasks

These are the structs that form our interface to Firestore:

- [x] `FirestoreRecurserDB`: #81 
- [x] `FirestoreAPIAuthDB`: #82 
- [ ] `FirestorePairingsDB`: TODO
- [x] `FirestoreReviewDB`: #93 

I think this refactor is a great first task for someone looking to get starting working on Pairing Bot. It should be possible to copy-paste from existing code and get quite far. And I would be also be glad to help out at any point (maybe even pair on it :wink:)!

Let me know (here or elsewhere) if you'd like to claim a struct :slightly_smiling_face:

**Comment by pjg11** [comment]
Was this supposed to be closed? The `PairingsDB` refactor is still mentioned in the checklist, and I'd like to work on it

**Comment by jdkaplan** [comment]
> Was this supposed to be closed? The `PairingsDB` refactor is still mentioned in the checklist, and I'd like to work on it

Good catch, thanks! And extra thanks for taking on `PairingsDB`!

**Comment by jdkaplan** [comment]
Thanks @pjg11 for finishing this up!
